package main

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"net"
	"testing"
	"time"

	"github.com/apernet/quic-go"
)

// TestParseRealQUICInitialFromGoClient feeds a real quic-go client's first
// Initial datagram through parseQUICInitial to prove the RFC 9001 decryption
// matches packets generated by the actual quic-go stack (not just the
// synthetic builder used by the unit tests).
func TestParseRealQUICInitialFromGoClient(t *testing.T) {
	serverRaw, err := net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4(127, 0, 0, 1)})
	if err != nil {
		t.Fatal(err)
	}
	defer serverRaw.Close()

	type captured struct {
		data []byte
		ok   bool
	}
	// A quic-go ClientHello often spans several Initial datagrams (MTU ~1200
	// bytes), so collect a handful and merge their CRYPTO frames.
	datagrams := make(chan []byte, 16)
	readDone := make(chan struct{})
	go func() {
		defer close(readDone)
		buf := make([]byte, 65536)
		serverRaw.SetReadDeadline(time.Now().Add(3 * time.Second))
		for i := 0; i < 16; i++ {
			n, _, err := serverRaw.ReadFromUDP(buf)
			if err != nil {
				return
			}
			datagrams <- append([]byte(nil), buf[:n]...)
		}
	}()

	clientUDP, err := net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4(127, 0, 0, 1)})
	if err != nil {
		t.Fatal(err)
	}
	defer clientUDP.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"h3"},
	}
	// Dial in a goroutine: there is no QUIC server to complete the handshake,
	// but the first Initials are sent immediately and are all we need.
	dialDone := make(chan error, 1)
	go func() {
		conn, err := quic.Dial(ctx, clientUDP, serverRaw.LocalAddr(), tlsConf, &quic.Config{})
		if err == nil {
			_ = conn.CloseWithError(0, "done")
		}
		dialDone <- err
	}()

	var cryptoBuf []byte
	deadline := time.After(5 * time.Second)
	for extractClientHello(cryptoBuf) == nil {
		select {
		case d := <-datagrams:
			pkt, err := parseQUICInitial(d)
			if err != nil {
				continue
			}
			for _, frag := range parseCryptoFrames(pkt.Payload) {
				cryptoBuf = mergeCryptoFrag(cryptoBuf, frag)
			}
		case <-deadline:
			t.Fatalf("timed out collecting complete ClientHello, cryptoBuf len=%d", len(cryptoBuf))
		}
	}
	if hello := extractClientHello(cryptoBuf); hello == nil || hello[0] != 0x01 {
		t.Logf("cryptoBuf len=%d head=%x", len(cryptoBuf), cryptoBuf[:min(len(cryptoBuf), 24)])
		t.Fatalf("no ClientHello extracted from real quic-go initial: %x", hello)
	}
	// Let the dial goroutine settle and release resources.
	select {
	case <-dialDone:
	case <-time.After(time.Second):
	}
}

// makeTestTLSConfig is a helper for H3 reality integration tests: it
// generates a self-signed TLS 1.3 config for the given DNS name.
func makeTestTLSConfig(t *testing.T, dnsName string) *tls.Config {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tmpl := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: dnsName},
		DNSNames:     []string{dnsName},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	return &tls.Config{
		Certificates: []tls.Certificate{{Certificate: [][]byte{der}, PrivateKey: key}},
		MinVersion:   tls.VersionTLS13,
		NextProtos:   []string{"h3"},
	}
}
