package main

import (
	"bytes"
	"context"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/apernet/quic-go"
)

type certificateCallbackConn struct {
	remote net.Addr
}

func (c certificateCallbackConn) Read([]byte) (int, error)         { return 0, nil }
func (c certificateCallbackConn) Write([]byte) (int, error)        { return 0, nil }
func (c certificateCallbackConn) Close() error                     { return nil }
func (c certificateCallbackConn) LocalAddr() net.Addr              { return nil }
func (c certificateCallbackConn) RemoteAddr() net.Addr             { return c.remote }
func (c certificateCallbackConn) SetDeadline(time.Time) error      { return nil }
func (c certificateCallbackConn) SetReadDeadline(time.Time) error  { return nil }
func (c certificateCallbackConn) SetWriteDeadline(time.Time) error { return nil }

func TestRealityTLSCertificateSignerCarriesConnectionProof(t *testing.T) {
	dir := t.TempDir()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tmpl := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: "example.test"},
		DNSNames:     []string{"example.test"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	certPath := filepath.Join(dir, "cert.pem")
	keyPath := filepath.Join(dir, "key.pem")
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(certPath, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keyPath, pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}), 0o600); err != nil {
		t.Fatal(err)
	}

	params := &realityQUICParams{
		Dest:           "example.test:443",
		DestServerName: "example.test",
		H3Cert:         certPath,
		H3Key:          keyPath,
	}
	tlsConf, authSource, err := buildRealityTLSConfig(context.Background(), params)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := authSource.AuthKeyFor(&net.TCPAddr{}); ok {
		t.Fatal("auth source unexpectedly returned a key before authentication")
	}

	authKey := bytes.Repeat([]byte{0x42}, 32)
	authSource.setLookup(func(net.Addr) ([]byte, bool) { return authKey, true })
	info := &tls.ClientHelloInfo{Conn: certificateCallbackConn{remote: &net.TCPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 44444}}}
	cert, err := tlsConf.GetCertificate(info)
	if err != nil {
		t.Fatal(err)
	}
	leaf, err := x509.ParseCertificate(cert.Certificate[0])
	if err != nil {
		t.Fatal(err)
	}
	if leaf.SubjectKeyId != nil {
		t.Fatalf("REALITY certificate unexpectedly changed SubjectKeyId: %x", leaf.SubjectKeyId)
	}
	signer, ok := cert.PrivateKey.(crypto.Signer)
	if !ok {
		t.Fatalf("certificate private key is %T, want crypto.Signer", cert.PrivateKey)
	}
	if !signer.Public().(interface{ Equal(crypto.PublicKey) bool }).Equal(leaf.PublicKey) {
		t.Fatalf("proof signer public key does not match certificate leaf")
	}
	signature, err := signer.Sign(rand.Reader, nil, crypto.Hash(0))
	if err != nil {
		t.Fatal(err)
	}
	if want := quicServerProof(authKey); !bytes.Equal(signature, want) {
		t.Fatalf("CertificateVerify proof mismatch: got %x, want %x", signature, want)
	}
}

// TestParseRealQUICInitialFromGoClient feeds a real quic-go client's first
// Initial datagram through parseQUICInitial to prove the RFC 9001 decryption
// matches packets generated by the actual quic-go stack (not just the
// synthetic builder used by the unit tests).
func TestParseRealQUICInitialFromGoClient(t *testing.T) {
	serverRaw, err := net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4(127, 0, 0, 1)})
	if err != nil {
		t.Fatal(err)
	}
	defer serverRaw.Close()

	// A quic-go ClientHello often spans several Initial datagrams (MTU ~1200
	// bytes), so collect a handful and merge their CRYPTO frames.
	datagrams := make(chan []byte, 16)
	readDone := make(chan struct{})
	go func() {
		defer close(readDone)
		buf := make([]byte, 65536)
		serverRaw.SetReadDeadline(time.Now().Add(3 * time.Second))
		for i := 0; i < 16; i++ {
			n, _, err := serverRaw.ReadFromUDP(buf)
			if err != nil {
				return
			}
			datagrams <- append([]byte(nil), buf[:n]...)
		}
	}()

	clientUDP, err := net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4(127, 0, 0, 1)})
	if err != nil {
		t.Fatal(err)
	}
	defer clientUDP.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"h3"},
	}
	// Dial in a goroutine: there is no QUIC server to complete the handshake,
	// but the first Initials are sent immediately and are all we need.
	dialDone := make(chan error, 1)
	go func() {
		conn, err := quic.Dial(ctx, clientUDP, serverRaw.LocalAddr(), tlsConf, &quic.Config{})
		if err == nil {
			_ = conn.CloseWithError(0, "done")
		}
		dialDone <- err
	}()

	var cryptoBuf []byte
	deadline := time.After(5 * time.Second)
	for extractClientHello(cryptoBuf) == nil {
		select {
		case d := <-datagrams:
			pkt, err := parseQUICInitial(d)
			if err != nil {
				continue
			}
			for _, frag := range parseCryptoFrames(pkt.Payload) {
				cryptoBuf = mergeCryptoFrag(cryptoBuf, frag)
			}
		case <-deadline:
			t.Fatalf("timed out collecting complete ClientHello, cryptoBuf len=%d", len(cryptoBuf))
		}
	}
	if hello := extractClientHello(cryptoBuf); hello == nil || hello[0] != 0x01 {
		t.Logf("cryptoBuf len=%d head=%x", len(cryptoBuf), cryptoBuf[:min(len(cryptoBuf), 24)])
		t.Fatalf("no ClientHello extracted from real quic-go initial: %x", hello)
	}
	// Let the dial goroutine settle and release resources.
	select {
	case <-dialDone:
	case <-time.After(time.Second):
	}
}
